IF NOT CONNECTED(dbacc) THEN
    CONNECT dbAcc NO-ERROR.
IF NOT CONNECTED(db001) THEN
    CONNECT db001 NO-ERROR.
IF NOT CONNECTED(db002) THEN
    CONNECT db002 NO-ERROR.

/*IF CONNECTED(logical-name)
THEN RUN procedure.
ELSE MESSAGE "DATABASE NOT AVAILABLE".
 RUN "egrad.p". 
    "QUIT". */

